# -*- coding: utf-8 -*-
"""task2_data_processing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uvEYaLLMPEyV-LnhVpVeBP3WgrRcz4vr
"""

import pandas as pd

# Load the JSON file from Task 1
file_path = "trends_20260410.json"
df = pd.read_json(file_path)

# Print how many rows were loaded
print(f"Loaded {len(df)} stories from {file_path}")

# Remove duplicate stories based on post_id
df = df.drop_duplicates(subset=["post_id"])
print(f"\nAfter removing duplicates: {len(df)}")

# Drop rows where post_id, title, or score is missing
df = df.dropna(subset=["post_id", "title", "score"])
print(f"After removing nulls: {len(df)}")

# Strip extra spaces from the title column
df["title"] = df["title"].astype(str).str.strip()

# Convert score and num_comments to numeric
df["score"] = pd.to_numeric(df["score"], errors="coerce")
df["num_comments"] = pd.to_numeric(df["num_comments"], errors="coerce").fillna(0)

# Convert to integers
df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].astype(int)

# Remove low-quality stories
df = df[df["score"] >= 5]
print(f"After removing low scores: {len(df)}")

# Save cleaned CSV
output_path = "trends_clean.csv"
df.to_csv(output_path, index=False)

# Confirmation
print(f"\nSaved {len(df)} rows to {output_path}")

# Category summary
print("\nStories per category:")
for category, count in df["category"].value_counts().items():
    print(f"{category}    {count}")

