# -*- coding: utf-8 -*-
"""task1_data_collection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lWpR6o5QKfsLrFzur2sGnMFXGu_sUBch
"""

import requests
import json
import os
import time
from datetime import datetime

# Base URLs for the Hacker News API
TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL_TEMPLATE = "https://hacker-news.firebaseio.com/v0/item/{}.json"

# Required header from the instructions
HEADERS = {"User-Agent": "TrendPulse/1.0"}

# Category keywords given in the project
CATEGORY_KEYWORDS = {
    "technology": ["AI", "software", "tech", "code", "computer", "data", "cloud", "API", "GPU", "LLM"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["NFL", "NBA", "FIFA", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "NASA", "genome"],
    "entertainment": ["movie", "film", "music", "Netflix", "game", "book", "show", "award", "streaming"]
}

MAX_IDS_TO_FETCH = 500
MAX_STORIES_PER_CATEGORY = 25


def get_top_story_ids():
    """
    Fetch the list of top story IDs from Hacker News.
    Returns the first 500 IDs, or an empty list if the request fails.
    """
    try:
        response = requests.get(TOP_STORIES_URL, headers=HEADERS, timeout=10)
        response.raise_for_status()
        story_ids = response.json()
        return story_ids[:MAX_IDS_TO_FETCH]
    except requests.RequestException as e:
        print(f"Failed to fetch top story IDs: {e}")
        return []


def get_story_details(story_id):
    """
    Fetch the details of a single story by its ID.
    Returns the story JSON as a dictionary, or None if the request fails.
    """
    try:
        url = ITEM_URL_TEMPLATE.format(story_id)
        response = requests.get(url, headers=HEADERS, timeout=10)
        response.raise_for_status()
        return response.json()
    except requests.RequestException as e:
        print(f"Failed to fetch story {story_id}: {e}")
        return None


def title_matches_category(title, keywords):
    """
    Check whether the story title contains any keyword for a category.
    Matching is case-insensitive.
    """
    title_lower = title.lower()
    for keyword in keywords:
        if keyword.lower() in title_lower:
            return True
    return False


def build_story_record(story, category):
    """
    Extract the required fields from a Hacker News story object
    and return them in the required output format.
    """
    return {
        "post_id": story.get("id"),
        "title": story.get("title", ""),
        "category": category,
        "score": story.get("score", 0),
        "num_comments": story.get("descendants", 0),
        "author": story.get("by", ""),
        "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }


def save_to_json(data):
    """
    Save the collected stories to a JSON file in the data folder.
    The filename format matches the instructions: trends_YYYYMMDD.json
    Returns the output file path.
    """
    os.makedirs("data", exist_ok=True)

    filename = f"trends_{datetime.now().strftime('%Y%m%d')}.json"
    output_path = os.path.join("data", filename)

    with open(output_path, "w", encoding="utf-8") as file:
        json.dump(data, file, indent=4, ensure_ascii=False)

    return output_path


def main():
    """
    Main pipeline:
    1. Fetch top story IDs
    2. For each category, scan stories and collect up to 25 matches
    3. Sleep 2 seconds after each category loop
    4. Save results to JSON
    """
    top_story_ids = get_top_story_ids()

    if not top_story_ids:
        print("No story IDs fetched. Exiting script.")
        return

    collected_stories = []
    collected_story_ids = set()

    # Process one category at a time, as suggested in the instructions
    for category, keywords in CATEGORY_KEYWORDS.items():
        category_count = 0

        for story_id in top_story_ids:
            if category_count >= MAX_STORIES_PER_CATEGORY:
                break

            # Avoid collecting the same story twice across categories
            if story_id in collected_story_ids:
                continue

            story = get_story_details(story_id)

            # Skip failed or invalid story objects
            if not story or not isinstance(story, dict):
                continue

            title = story.get("title", "")

            # Skip stories without a title
            if not title:
                continue

            # Add the story if its title matches the current category
            if title_matches_category(title, keywords):
                record = build_story_record(story, category)
                collected_stories.append(record)
                collected_story_ids.add(story_id)
                category_count += 1

        # Sleep once after each category loop, not after each request
        time.sleep(2)

    output_file = save_to_json(collected_stories)
    print(f"Collected {len(collected_stories)} stories. Saved to {output_file}")


if __name__ == "__main__":
    main()

from google.colab import files
files.download('data/trends_' + __import__('datetime').datetime.now().strftime('%Y%m%d') + '.json')

