# -*- coding: utf-8 -*-
"""task3_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gK09Su2tki_ADX4sUeqwj6oEQmcZ_q3Q
"""

# importing necessary the libraries
import pandas as pd
import numpy as np

# l'oading the file
df = pd.read_csv("trends_clean.csv")

# print the data
print(df.head())
print(df.shape)

# print averages
print("Average score:", df['score'].mean())
print("Average comments:", df['num_comments'].mean())

# BASIC ANALYSIS USING NUMPY
# Mean, median, std of score

import numpy as np

scores = df['score'].values

print("Mean:", np.mean(scores))
print("Median:", np.median(scores))
print("Std Dev:", np.std(scores))

# Highest and lowest score
print("Max score:", np.max(scores))
print("Min score:", np.min(scores))

# Category with most stories
print(df['category'].value_counts().idxmax())

# Story with most comments
top_story = df.loc[df['num_comments'].idxmax()]
print(top_story['title'], top_story['num_comments'])

# Add New Columns
df['engagement'] = df['num_comments'] / (df['score'] + 1)

avg_score = df['score'].mean()
df['is_popular'] = df['score'] > avg_score

# Save Result
df.to_csv("trends_analysed.csv", index=False)
print("Saved successfully")

# checking whether new comments are created
print(df.head())

