# -*- coding: utf-8 -*-
"""task4_visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Z_tVWvqtfzoXevCHRleLX2uSx6S4PEK
"""

import os
import pandas as pd
import matplotlib.pyplot as plt

# Load the analysed CSV from Task 3
df = pd.read_csv("trends_analysed.csv")

# Create outputs folder if it does not exist
os.makedirs("outputs", exist_ok=True)

# -------------------------------
# Chart 1: Top 10 Stories by Score
# -------------------------------

# Sort by score and take top 10 stories
top_10 = df.sort_values(by="score", ascending=False).head(10).copy()

# Shorten titles longer than 50 characters
top_10["short_title"] = top_10["title"].apply(
    lambda x: x[:50] + "..." if len(x) > 50 else x
)

plt.figure(figsize=(10, 6))
plt.barh(top_10["short_title"], top_10["score"])
plt.title("Top 10 Stories by Score")
plt.xlabel("Score")
plt.ylabel("Story Title")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig("outputs/chart1_top_stories.png")
plt.close()

# -------------------------------
# Chart 2: Stories per Category
# -------------------------------

# Count how many stories are in each category
category_counts = df["category"].value_counts()

plt.figure(figsize=(8, 5))
plt.bar(
    category_counts.index,
    category_counts.values,
    color=["blue", "green", "red", "orange", "purple"]
)
plt.title("Stories per Category")
plt.xlabel("Category")
plt.ylabel("Number of Stories")
plt.tight_layout()
plt.savefig("outputs/chart2_categories.png")
plt.close()

# -------------------------------
# Chart 3: Score vs Comments
# -------------------------------

# Separate popular and non-popular stories
popular = df[df["is_popular"] == True]
not_popular = df[df["is_popular"] == False]

plt.figure(figsize=(8, 6))
plt.scatter(popular["score"], popular["num_comments"], color="blue", label="Popular")
plt.scatter(not_popular["score"], not_popular["num_comments"], color="red", label="Not Popular")
plt.title("Score vs Comments")
plt.xlabel("Score")
plt.ylabel("Number of Comments")
plt.legend()
plt.tight_layout()
plt.savefig("outputs/chart3_scatter.png")
plt.close()

# -------------------------------
# Bonus: Dashboard
# -------------------------------

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle("TrendPulse Dashboard")

# Dashboard chart 1
axes[0].barh(top_10["short_title"], top_10["score"])
axes[0].set_title("Top 10 Stories by Score")
axes[0].set_xlabel("Score")
axes[0].set_ylabel("Story Title")
axes[0].invert_yaxis()

# Dashboard chart 2
axes[1].bar(
    category_counts.index,
    category_counts.values,
    color=["blue", "green", "red", "orange", "purple"]
)
axes[1].set_title("Stories per Category")
axes[1].set_xlabel("Category")
axes[1].set_ylabel("Number of Stories")

# Dashboard chart 3
axes[2].scatter(popular["score"], popular["num_comments"], color="blue", label="Popular")
axes[2].scatter(not_popular["score"], not_popular["num_comments"], color="red", label="Not Popular")
axes[2].set_title("Score vs Comments")
axes[2].set_xlabel("Score")
axes[2].set_ylabel("Number of Comments")
axes[2].legend()

plt.tight_layout()
plt.savefig("outputs/dashboard.png")
plt.close()

print("All charts saved successfully in outputs/")

